name: timeline_slider
description: A customizable horizontal timeline slider widget for Flutter.
version: 0.0.7
homepage: https://github.com/levanhiendev/timeline_slider
license: MIT

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
